CREATE TABLE IF NOT EXISTS PESSOA (
	IDPESSOA SERIAL PRIMARY KEY,
	NOME VARCHAR(100),
	DOCUMENTO VARCHAR(20),
	CELULAR VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS PRODUTO (
	IDPRODUTO SERIAL PRIMARY KEY,
	NOME VARCHAR(100),
	CODERP VARCHAR(20),
	PRECO NUMERIC(10,2)
);

CREATE TABLE IF NOT EXISTS COMPRA (
	IDCOMPRA SERIAL PRIMARY KEY,
	IDCOMPRA INT,
	IDPESSOA INT,
	DATACOMPRA DATE,
	CONSTRAINT FK_PESSOA_COMPRA FOREING KEY(IDPESSOA) REFERENCES PESSOA(IDPESSOA),
	CONSTRAINT FK_PRODUTO_COMPRA FOREING KEY(IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO),
);

